
import Link from 'next/link'
import React from 'react'

export const metadata = {
  title: 'تفسير',
  description: 'Generated by create next app',
}

export default async function Tafasir() {

  async function getTafasir(){
    const response = await fetch('https://www.mp3quran.net/api/v3/recent_reads?language=ar').catch((err)=> err)
    const finalRes = response.json()
    return finalRes
  }
  const {reads} = await getTafasir()

  return (
    <>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-10 my-5">


    {reads.map((read,index)=>{
      return <div key={index} className='border border-[#666] p-5 rounded-lg text-center hover:bg-[--mainColor] duration-300 cursor-pointer'>
        <Link href={read.moshaf[0].server}>
        <h1>{read.name}</h1>
        <hr className='my-3'/>
        <div className='flex justify-between items-center py-5'>
          <p className='text-[11px]'>{(read.recent_date).split('T')[0]}</p>
        <p className='text-[13px]'>{read.moshaf[0].name}</p>
        </div>
        </Link>
      </div>
    })}
    
    </div>
    </>
  )
}
