
import Image from 'next/image'
import Link from 'next/link'
import React from 'react'

export const metadata = {
  title: 'تدبر',
  description: 'Generated by create next app',
}

export default async function Tadabar() {
  async function getTadabar(){
    const response = await fetch('https://mp3quran.net/api/v3/tadabor?sura=3&language=ar').catch((err)=> err)
    const finalRes = response.json()
    return finalRes
  }
  const {tadabor} = await getTadabar()
  return (
    <>
    
    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-10 my-5">
       {tadabor['3'].map((card)=>{
          return <div className="box mx-auto bg-[--mainColor] rounded-2xl shadow-xl" key={card.id} 
      
          >
            <Link href={card.video_url}>
            <Image
            src={card.image_url}
            className='w-full rounded-t-lg'
            width={180}
            height={100}
            alt={card.reciter_name}
            />
      
              <h3 className='text-center py-3 font-bold'>{card.reciter_name}</h3>
              </Link>
        
          </div>
        })} 

    </div>
    </>

  )
}
