
import Link from 'next/link'
import React from 'react'

export const metadata = {
  title: 'لايف',
  description: 'Generated by create next app',
}

export default async function Live() {

  async function getLive (){
    const response = await fetch('https://mp3quran.net/api/v3/radios').catch((err)=> err)
    const finalRes = response.json()
    return finalRes
  }
  const {radios} = await getLive()

  return (
    <>
    <h2 className='text-center my-5 border w-fit rounded-full mx-auto py-3 px-5'>للاستماع مباشر </h2>

    <div className="grid md:grid-cols-2 lg:grid-cols-2 gap-10 my-5 text-center ">
      {radios?.map((radio)=>{
        return <div className='border py-5 rounded-xl bg-[--mainColor] flex justify-between px-4 items-center md:text-sm md:flex-col-reverse lg:text-md lg:flex-row ' key={radio.id}>


          <Link href={radio.url} className=" hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4  rounded shadow bg-blue-300 flex items-center duration-300 md:mt-5 lg:mt-0">
            <i className="fa-solid fa-play me-2"></i>
            <p >الاستماع الان</p>
          </Link>

          <h3 className='text-md font-semibold'>{radio.name}</h3>
        
        </div>
      })}
    </div>
    </>
  )
}
