
import './globals.css'
import Slidebar from './(components)/Slidebar/Slidebar'
import Navbar from './(components)/Navbar/Navbar'
import '@fortawesome/fontawesome-free/css/all.min.css'
import ScrollTop from './(components)/ScrollTop/ScrollTop'
import Footer from './(components)/Footer/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children}) {
  
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet"/>
      </head>
      <body> 

        <div className="container mx-auto py-4">
        <div className="grid grid-cols-12 justify-between">

      <div className="hidden md:flex col-span-3 ">
        <div className="fixed w-1/4 left-0 top-5 z-1 mx-2">

        <Slidebar/>
        </div>
      </div>

      <div className="col-span-12 md:col-span-9  md:mx-5 outlet min-h-screen rounded-lg">
        <Navbar/>
        
    <div className='px-3'>

        {children}
      <ScrollTop/>
    </div>
    



    
<Footer/>
      </div>
        </div>

      </div>
        
        </body>
    </html>
  )
}
